### ISSUE TITLE
Relocate to JuliaMath?

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/Polynomials.jl#109]
It seems this package would be a good fit for the JuliaMath organization, and @jverzani, the top contributor here, is also an active contributor in JuliaMath. Keno admittedly doesn't watch this package all that closely these days, and has expressed willingness to make the move should John deem it a good idea. In that case I can give Keno the necessary JuliaMath permissions to make the move.

**Comment by jverzani** [comment]
Great idea if @keno thinks so.

**Comment by ararslan** [comment]
The deed is done.
