### ISSUE TITLE
eachindex

### ISSUE THREAD

**Issue by jverzani** [JuliaMath/Polynomials.jl#118]
In discussion #117 the absence of `eachindex` came up. This should be added so that expressions such as `[p[i] * variable(p)^i for i in eachindex(p)]` work.

**Comment by aytekinar** [comment]
Will you fix this, or shall I create a PR?

**Comment by jverzani** [comment]
Either way, it wasn't as critical as merging in your fix, so I left as a task for later. A PR would be welcome, but I'll get to it if you don't first.
