### ISSUE TITLE
Meaningless truncate()

### ISSUE THREAD

**Issue by ivanslapnicar** [JuliaMath/Polynomials.jl#120]
In the code section
```
function roots{T}(p::Poly{T})
    R = promote_type(T, Float64)
    length(p) == 0 && return zeros(R, 0)
    p = truncate(p)
    ...
```
the polynomial 
`p=8.362779449448982e41 - 2.510840694154672e57∙x + 4.2817430781178795e44∙x^2 - 1.6225927682921337e31∙x^3 + 1.0∙x^4`

gets truncated to `p=truncate(p)=-2.510840694154672e57∙x` so the roots(p) returns just one root 0.0.
This is wrong and meaningless. When the line `p = truncate(p)` is removed from the roots() function, `roots(p)` returns correct roots
```
1.62259e31
 1.75922e13
 8.79609e12
 0.0       
```
So, forcing truncate() is counterproductive. Just leave the polynomial as is and let the eigvals() routine do its job.

**Comment by jverzani** [comment]
Thanks for the feedback. I have a PR in #121  to make this change. Will merge soon if there is no concern expressed. Users can manually call `truncate` if desired.

**Comment by ivanslapnicar** [comment]
Dear John!
Thank you for your answer. I find your proposal the best one.
Best regards, Ivan
