### ISSUE TITLE
drop support for v0.4

### ISSUE THREAD

**Issue by jverzani** [JuliaMath/Polynomials.jl#126]
and possibly v0.5. This can eliminate compat calls and will need to be done when 0.7 comes around.

**Comment by tkelman** [comment]
We're actually likely to freeze METADATA for 0.4-supporting packages pretty soon. Exceptions can be made, but I'd prefer to only do so for packages that aren't depended on by anything else to minimize the potential problems.

If you decide to drop both 0.4 and 0.5 at the same time, it would be a good idea to increment the package minor version by 2 at the next tag, just in case there's ever a need to backport fixes, would be good to leave versioning room for an 0.4-supporting series, a possible 0.5-supporting series of backports (only to be used if really needed), and an 0.6-only series for master.
