### ISSUE TITLE
Python/Sage like behavior for `coeffs`?

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaMath/Polynomials.jl#129]
is it worth it to have a feature for `coeffs` so that if you can 1) ask for a specific coefficient, 2) if you ask outside of the degree it returns 0.

Something like:
```julia
function Polynomials.coeffs(p::Poly, k::Int)
    k < 0 && throw(DomainError("Coefficient index must be non-negative))
    if k > degree(p)
        return zero(eltype(p))
    else
        return coeffs(p)[k + 1]
    end
end
```

For some code this can be useful so that you can fold together polynomials with different degrees in a general way.

**Comment by jverzani** [comment]
the idiom is p[k]--mapping p to a 0-based vector--isn't that easier? (I'm not sure what fold means here) I'd prefer one way, but let's see what others say, the change is easy.

**Comment by gabrielgellner** [comment]
You are absolutely correct! I didn't realize that directly indexing the `Poly` worked liked I expected (I always worked by indexing the return from `coeffs`). Thanks so much. I now personally wouldn't want the change, as I simply misunderstood the API.

**Comment by jverzani** [comment]
Okay, thanks for taking the time to make a suggestion.
