### ISSUE TITLE
Root finder for large problems

### ISSUE THREAD

**Issue by andreasnoack** [JuliaMath/Polynomials.jl#13]
Alan sent me a copy of [this](http://www.cs.kuleuven.be/publicaties/rapporten/tw/TW654.abs.html) which is a clever way to calculate eigenvalues of a companion matrix. They also provide their Fortran code which I have wrapped in an unregistered [package](https://github.com/andreasnoack/AMVW.jl), but I think it would make sense to merge it into this package. Any objections?

**Comment by hrobotron** [comment]
Any private progress on this topic? Would be interesting to compare the KU Leuven algorithm to a8c9302;
and if there were no performance penalty, I'd opt for the faster algorithm. If you have the Fortran code running, please test against a8c9302 and if the outcome will be positive, let's consider porting to native Julia.

Also, do you have any author feedback on licensing?

**Comment by andreasnoack** [comment]
Just checked my email and Watkins replied that he is fine with MIT license for the AMVW code. There is no doubt that AMVW code can handle much larger problems and I think it is faster for all problem sizes. It would be great to use the AMVW functionality for finding roots in this package. It would either require that we find a way to supply binaries of the Fortran code or port the code to Julia. Right now, I don't have much time to do any of these but if you are interested in trying it out, I can try to help.

**Comment by hrobotron** [comment]
I'd definitely opt for porting to native Julia. I will await whether my other pull requests will find their way to the pkg, then I may consider investing some work into trying and porting the AMVW code. BTW, if you have the code running (outside of Julia), can you just run few tests, what will be errors of Fortran AMVW compared to  a8c9302 roots? I mean
<pre>r=something (randn, real, complex,...)
r1=roots(poly(r))
r=sort(r, lt=(a,b)->(real(a)&lt;real(b)||imag(a)&lt;imag(b)))
r1=sort(r1, lt=(a,b)->(real(a)&lt;real(b)||imag(a)&lt;imag(b)))
e=r1-r
maximum(abs(e))
</pre>
or <code>std(e)</code>.

It would be great to assure the AMVW will not give worse results, prior to replace the very standard way using full O(n^2) companion matrix. No doubt it will be faster, though.

**Comment by jverzani** [comment]
Your other pull request will find its way in soon. I was going to ask you to add a test, but see you've already got there. This would be a good addition in my opinion, though it might be best in an independent package at the outset.

**Comment by jverzani** [comment]
This  was done  in https://github.com/jverzani/AMRVW.jl
