### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaMath/Polynomials.jl#153]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by martinholters** [comment]
The automatic capping resulted in versions up to 0.4 being capped to Julia 0.7, versions 0.5 and up not being capped. A brief test with Julia 1.0 confirms that 0.4.0 fails its tests (as does 0.3.3), but 0.5.0 works. So the caps seem to be correct and the issue can be closed, or am I missing something?
