### ISSUE TITLE
Wrong curve fitting with large polynomial degree

### ISSUE THREAD

**Issue by aborzunov** [JuliaMath/Polynomials.jl#154]
I have an experimental data set with 130k entries.

When I do `polyfit(x,y, n)` i get some strange results if `n` is more than 7.

- Blue is original data
- orange curve is deg = 3
- yellow curve is deg = 5
- red curve is deg = 11
- green curve is deg = 20

![newplot](https://user-images.githubusercontent.com/2773341/46790282-40e63180-cd47-11e8-998b-09b7a014dee6.png)

Is this an issue or i missing something?

**Comment by jverzani** [comment]
Just guessing, but the range of the data is pretty large (75^11 becomes quite big.) What happens if you scale the data to a range like (-1,1), fit the data, the unscale? This *might* avoid some numeric issues.
