### ISSUE TITLE
CONJ cannot be found

### ISSUE THREAD

**Issue by hurak** [JuliaMath/Polynomials.jl#155]
In Julia v1.0.1 with Polynomials v0.5.1, it appears that `conj` function for Polynomials cannot be found
```
julia> a = Poly(1:3)
Poly(1 + 2*x + 3*x^2)

julia> conj(a)
ERROR: MethodError: no method matching conj(::Poly{Int64})
Closest candidates are:
  conj(::Missing) at missing.jl:79
  conj(::Real) at number.jl:191
  conj(::Complex) at complex.jl:259
  ...
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by jverzani** [comment]
Yes, for some reason, we have restricted the type:

```
conj(p::Poly{T}) where {T<:Complex} = Poly(conj(coeffs(p)))
```

I think this was due to some transient change in calling `conj` for real numbers. It seems lke it could be relaxed now. Would you care to put in a pull request and see if the tests pass? If not, I can look into it, but not for awhile.
