### ISSUE TITLE
norm function undefined

### ISSUE THREAD

**Issue by hurak** [JuliaMath/Polynomials.jl#158]
Hi, the norm function is undefined in recent stable version of Polynomials (v0.5.1) and Julia (v1.0.1):
```
using Polynomials

julia> a = Poly(1:3)
Poly(1 + 2*x + 3*x^2)

julia> norm(a)
ERROR: UndefVarError: norm not defined
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by jverzani** [comment]
Yes, thanks. This is a v0.6 legacy thing. In the interim, you can call `using LinearAlgebra`, then `norm` should work.

**Comment by jverzani** [comment]
Likely all of these ` norm, dot, eigvals, diagm` are similar. I don't know what is best here, you may have thoughts, but for now we import these from LinearAlgebra  in the package and define methods for polynomials, but the names aren't exported by Polynomials, so aren't available until LinearAlgebra is loaded. Unless there are some compelling reasons, this seems like a reasonable strategy.
