### ISSUE TITLE
zero(Poly{T}), one(Poly{T}) 

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Polynomials.jl#162]
e.g. 
```
zero(::Type{Poly{T}}) where {T} = Poly([zero(T)])
one(::Type{Poly{T}}) where {T} = Poly([one(T)])
```

**Comment by jverzani** [comment]
Aren't these defined already (https://github.com/JuliaMath/Polynomials.jl/blob/master/src/Polynomials.jl#L292)? The `zero` defn. is different, but essentially identical.

**Comment by JeffreySarnoff** [comment]
yes -- they are
