### ISSUE TITLE
Plotting polynomials should "just work"

### ISSUE THREAD

**Issue by hardbyte** [JuliaMath/Polynomials.jl#168]
Plotting works quite intuitively in Julia, e.g. an anonymous function can be plotted as simply as:

![image](https://user-images.githubusercontent.com/855189/58376172-96561280-7fa7-11e9-9385-31e84e73f6e0.png)

However this lovely user experience isn't replicated when using Polynomials.jl:

![image](https://user-images.githubusercontent.com/855189/58376179-b5ed3b00-7fa7-11e9-94f5-8545b3b54262.png)

**Comment by hardbyte** [comment]
For what it is worth here is what I ended up with for my particularly needs:

```julia
@recipe function plot(p::Poly{Int64}, n::Integer = 100)
    c = roots(p)
    span = (maximum(c) - minimum(c))/5
    (p, range(minimum(c) - span, stop=maximum(c) + span, length=n))
end

@recipe function plot(p::Poly{Int64}, x::AbstractRange{Number})
    y = map(p, x)
    seriestype --> :path
    title --> repr("text/plain", p)
    x, y
end

@recipe function plot(p::Poly{Int64}, x::AbstractArray{Real,1}) where T
    y = map(p, x)
    seriestype --> :path
    title --> repr("text/plain", p)
    x, y
end
```

**Comment by jverzani** [comment]
Maybe put in a PR? It adds a dependency though, so maybe there will be some push back. I'd also suggest checking the real roots of the function and its derivative to find the informative points to identify the interval to plot over when not specified.

**Comment by jverzani** [comment]
I forget when, but a recipe got added. Thanks if it  was you :)
