### ISSUE TITLE
polyfit doesn't return the same length array as order if it is 0

### ISSUE THREAD

**Issue by scottstanie** [JuliaMath/Polynomials.jl#170]
This behavior is a little unexpected to me: when asking for an order 1 polynomial, there will always be 2 coefficients (the `a, b` in `ax + b`)
```
julia> Polynomials.coeffs(Polynomials.polyfit(1:10, 1:10, 1))
2-element Array{Float64,1}:
 1.4896608000791264e-15
 1.0

julia> Polynomials.coeffs(Polynomials.polyfit(ones(10), ones(10), 1))
2-element Array{Float64,1}:
 0.4999999999999999
 0.4999999999999997
```
...unless it is zero
```
julia> Polynomials.coeffs(Polynomials.polyfit(zeros(10), zeros(10), 1))
1-element Array{Float64,1}:
 -0.0
```
This means if I have code that wants the slope and offset:
```
offset, slope = Polynomials.coeffs(Polynomials.polyfit(ones(10), ones(10), 1))
``` 
it will error if my data ends up being zero:
```
julia> offset, slope = Polynomials.coeffs(Polynomials.polyfit(zeros(10), zeros(10), 1))
ERROR: BoundsError: attempt to access 1-element Array{Float64,1} at index [2]
Stacktrace:
 [1] getindex at ./array.jl:729 [inlined]
 [2] indexed_iterate(::Array{Float64,1}, ::Int64, ::Int64) at ./tuple.jl:64
 [3] top-level scope at none:0
```

Is it reasonable to make the polynomial also have the same length coefficient array? If so, should i put in a PR for this?

**Comment by jverzani** [comment]
#175 allows you to call `polyfit` and return the computed coefficients before they are passed to the `Poly` constructor. I used a type to disambiguate the calls, in place of a different name (e.g., `_polyfit(x,y,n)`) which might make more sense, but that wouldn't be exported.
