### ISSUE TITLE
Description of degree of a (zero) polynomial on the github webpage

### ISSUE THREAD

**Issue by hurak** [JuliaMath/Polynomials.jl#171]
On the [very front webpage here on github](https://github.com/JuliaMath/Polynomials.jl), an example is given
```
p = Poly([1, 2, 3], :x)
```
First but minor (yet potentially confusing) issue is that immediately in the next block this code is followed by
```
degree(p)
```
which, accoding to the webpage, returns `1` while if run in Julia for the above introduced  polynomial `p`, the result is `2`. I assume that the newcomers to Polynomials.jl (similarly as myself) are just picking the pieces of code from the webpage and run them one line after another. Therefore I suggest modifying the output of the example(s) on the webpage accordingly.

Second issue is perhaps a little bit more troubling. The page shows that
```
degree(p-p)
```
returns `0` but when I run this code myself (Julia v1.2 but also v0.7), I get `-1`.

In fact, even the help for the `degree()` function states that

> The degree of the zero polynomial is defined to be -1.

I assume that this only reflects the fact that at some point in developing the package a decision was made to shift from `degree(p-p) = 0` to `degree(p-p) = -1` but it would be great if consistently reflected on the github webpage.

**Comment by jverzani** [comment]
Closed by #172
