### ISSUE TITLE
polyfit example error due to missing broadcast in exp

### ISSUE THREAD

**Issue by iuliancioarca** [JuliaMath/Polynomials.jl#181]
I ran the polyfit example:
``
xs = 1:4; ys = exp(xs); polyfit(xs, ys)
``
and ran into an error. The exp call is missing a dot for broadcasting:
``
xs = 1:4; ys = exp.(xs); polyfit(xs, ys)
``

**Comment by jverzani** [comment]
Thanks! This example predates the deprecation of vectorized `exp`. We will have to change it. Care to put in a PR?

**Comment by jverzani** [comment]
This was closed in #196 (if not before). Thanks again.
