### ISSUE TITLE
Should polyfit accept error bars or covariance matrices?

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/Polynomials.jl#183]
It is common to work with data that has error bars or that has a non-diagonal covariance matrix. It's easy to extend polyfit to accept these cases. I've created https://github.com/jishnub/PolyFit.jl to implement this for the time being, but Polynomials.jl seems the right place for it. If this seems ok I can submit a PR.

**Comment by jverzani** [comment]
Hmm, maybe polynomials is the right place, or maybe polyfit should be left to your package. I personally like that better, as it is less to maintain on the `Polynomials` end and your implementation is faster and more general! Have you registered `PolyFit`?

**Comment by jishnub** [comment]
Sure. I have not registered Polyfit yet, but will do it in that case. Also it's really only faster for a special case of fitting a (n-1)-degree polynomial to n points at the moment, but I hope something more general might be found. Thanks anyway!
