### ISSUE TITLE
Poly() --> Polynomial()?

### ISSUE THREAD

**Issue by B-LIE** [JuliaMath/Polynomials.jl#206]
I assume that the documentation for `Polynomials.jl` has been upgraded the last couple of days, in that the constructor appears to be `Polynomial` instead of `Poly`, perhaps due to the inclusion of Chebycheff polynomial, etc. Another change seems to be changing `poly()` to `fromroots()`. 

Three questions related to this change:
1. If I update `Polynomials`, will my old code with `Poly`, `poly`, etc. stop working, or is there a "grace" period when both sets of commands will work?

2. I've already touched upon the problem of Broadcasting in another thread.

3. You have included function `gcd()`. Any plans to include a function `lcm`, or is it trivial to compute it from `gcd()`?

**Comment by jverzani** [comment]
Version 0.9 has warnings about needing to use `using Polynomials.PolyCompat` to utilize the old commands and types, but beyond that your old code should work as is. But going forward, the new framework allows us to have multiple bases represented with the same code base. Chebyshev is one example, as is ImmutablePolynomial (and the old Poly type too). 

As for lcm, we could I suppose. No one ever asked. The computation in floating point is so unreliable, but  I think if one wanted to use rational numbers and had smallish numbers it should be fine. Want to make a PR with a suggested implementation?

**Comment by B-LIE** [comment]
LCM... not a big hurry for me. I have never really used Github (although I have an account), so I need some time to learn that first. I'm trying to work out some code related to ControlSystems package (polynomial matrix fraction description) -- not because I think many has asked for it, but as a way of (i) learning to create composite types and more, (ii) recapturing some half forgotten control theory. 

More interesting would be an algorithm for Smith form of a matrix, but I assume you focus on basic polynomials and not on matrices of polynomials.

I may get back with a couple of suggestions for polynomial fit, though. But that's another story.
