### ISSUE TITLE
Differences between Polynomial and Poly

### ISSUE THREAD

**Issue by ymocquar** [JuliaMath/Polynomials.jl#208]
p1=Polynomial([1//1])
p2=Polynomial([0, 0.9x])
p3=p1(p2)
--- p3 = 1//1

p1=Poly([1//1])
p2=Poly([0, 0.9x])
p3=p1(p2)
--- p3 = Poly(1.0)

Note that there are two differences.
First the result with Polynomial is a scalar,
Second the type of this scalar with Polynomial is rational.
I think that the result with Poly is more logical for both.

Regards,
Yves Mocquard

**Comment by jverzani** [comment]
Thanks. We changed the evaluation to use the new `evalpoly` of Julia 1.4 and didn't adjust the algorithm to consider the type  of `x` when starting out. I will make a change to get the old behaviour back.

**Comment by jverzani** [comment]
This should be fixed now.
