### ISSUE TITLE
LATEST Documentation actually directs to the old POLY version 

### ISSUE THREAD

**Issue by hurak** [JuliaMath/Polynomials.jl#227]
When selecting LATEST on [https://juliamath.github.io/Polynomials.jl/latest/](https://juliamath.github.io/Polynomials.jl/latest/), a documentation page featuring the old syntax based on `poly` constructor (was it pre v0.7 version?) opens. If STABLE is chosen instead, the new syntax with the new `polynomial` constructor is shown.

**Comment by jverzani** [comment]
Thanks for letting me know.
