### ISSUE TITLE
Error in trying to use an iterator in fit()

### ISSUE THREAD

**Issue by jprhyne** [JuliaMath/Polynomials.jl#228]
![ErrorInPolynomial](https://user-images.githubusercontent.com/55465012/82847091-2a5c0200-9eba-11ea-8a2e-1b3419d85336.png)
Above is a screenshot of an error I encountered when I was trying to use an iterator with the fit function.
Below is an image of what fixed the issue
![ExpectedOutPut](https://user-images.githubusercontent.com/55465012/82847124-58414680-9eba-11ea-981b-c7f7790367fd.png)

After looking into line 93 in the proper file, I am not sure what is causing the issue because even though promote doesn't replace the original typings, the proper type gets passed.

Attached is my output from versioninfo() in case this is a version specific issue, and if it is the case, then you can close this as that would be caused by my stubbornness in wanting to wait to upgrade until this project is done.

```
    Julia Version 1.3.1 
    Commit 2d5741174c (2019-12-30 21:36 UTC) 
    Platform Info: 
    OS: Linux (x86 64-pc-linux-gnu) 
    CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz 
    WORD SIZE: 64 
    LIBM: libopenlibm 
    LLVM: libLLVM-6.0.1 (ORCJIT, sandybridge) 
```

edit: mProbBound is an Array of size 100x1 in case that was not clear, and ngrid gives 100 elements, so sizes match up

**Comment by jverzani** [comment]
Thanks!  This will be fixed in  #229
