### ISSUE TITLE
Bug: unexpected output of Polynomials

### ISSUE THREAD

**Issue by jakewilliami** [JuliaMath/Polynomials.jl#233]
Version information:
```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```
```
julia> using Polynomials, SymPy
julia> @vars A B C Z real=true
(A, B, C, Z)
julia> A*Polynomial([1,2], :Z)^2+B*Polynomial([1,-1], :Z)*Polynomial([1,2], :Z)+C*Polynomial([1,-1], :Z)
Polynomial(A + B + C + 4*A + B - C*Z + 4*A - 2*B*Z^2)
```
This output is incorrect: it should be `Polynomial(A + 4*A*Z + 2*A*Z^2 + B + B*Z + 2*B*Z^2 + C - C*Z)`.  However, it isn't that Julia is calculating the polynomial correctly, because by dumping information we see that the coefficients are indeed correctly what it should be:
```
julia> dump(A*Polynomial([1,2], :Z)^2+B*Polynomial([1,-1], :Z)*Polynomial([1,2], :Z)+C*Polynomial([1,-1], :Z))
Polynomial{Sym}
  coeffs: Array{Sym}((3,)) Sym[A + B + C, 4*A + B - C, 4*A - 2*B]
  var: Symbol Z
```
Which expands to `(A + B + C) + Z*(4*A + B - C) + Z^2*(4*A - 2*B)` (which is the correct answer).  This means that the polynomial is being calculated correctly but printed incorrectly.

**Comment by jverzani** [comment]
I’m guessing it is this https://github.com/JuliaMath/Polynomials.jl/blob/master/src/show.jl#L184

**Comment by olof3** [comment]
Was there any progress on this?

@jverzani I guess you are the right person to solve this problem at the interface of Polynomials and SymPy :) 

Here is slightly more minimal example
```julia
using SymPy
using Polynomials
@syms a
Polynomial([a, a^2 + 1])
# prints Polynomial(a + a^2 + 1*x)
```

**Comment by jverzani** [comment]
This one requires the user to do something. In the documentation for `printcoefficient` there is an example. Here it is  modified for this usage:

```
julia> using SymPy

julia> @syms a
(a,)

julia> Polynomial([a, a^2 + 1])
Polynomial(a + a^2 + 1*x)

julia> function Base.show_unquoted(io::IO, pj::SymPy.SymbolicObject, indent::Int, prec::Int)
              if Base.operator_precedence(:+) <= prec
                   print(io, "(")
                   show(io, pj)
                   print(io, ")")
               else
                   show(io, pj)
               end
           end

julia> Polynomial([a, a^2 + 1])
Polynomial((a) + (a^2 + 1)*x)
```

(Which isn't perfect, as that (a) is annoying.)

In typing this up, it occurs to me that it might be best to expose some easier way to register such a method.

BTW, there are naming conflicts between these two packages (`degree` and `roots` come to mind)

**Comment by olof3** [comment]
Thanks!

So the fix in this case would be to define the correct version of `Base.show_unquoted` in SymPy? Preferably accounting for that single symbols should be parenthesized?

**Comment by jverzani** [comment]
Well, now that you mention that... It seems that could certainly be done to solve this paired usage.

**Comment by jverzani** [comment]
https://github.com/JuliaPy/SymPy.jl/pull/423 should close this

**Comment by olof3** [comment]
Many thanks for the quick fix @jverzani !

**Comment by jverzani** [comment]
Closed by fix to SymPy. Please reopen if this isn't satisfactory.
