### ISSUE TITLE
A question about some design decisions for LaurentPolynomial

### ISSUE THREAD

**Issue by hurak** [JuliaMath/Polynomials.jl#254]
Having worked a bit with `LaurentPolynomial` type lately, I am wondering what was the motivation for one particular implementation aspect. Namely, the *range* `m:n` for the powers of the independent variable. In the example

```julia
julia> a = LaurentPolynomial([1,2,3,4],-2:1,:z)
LaurentPolynomial(z⁻² + 2*z⁻¹ + 3 + 4*z)
```
the second parameter is the range `-2:1`.

I like viewing Laurent polynomials as just a minor extension of standard polynomials. Or the other way round - standard polynomials as just a specialization of Laurent polynomials in that the lower degree (the `m` parameter) is set to zero. Indeed, setting the parameter `m` nonzero (EDIT: negative) is the step needed to transition from a standard to a Laurent polynomial. With standard polynomials we do not specify the "upper degree" (or just degree) when defining them. We just write

```julia
julia> b = Polynomial([1,2,3,4],:z)
Polynomial(1 + 2*z + 3*z^2 + 4*z^3)
```
and the lower degree `m` is assumed zero and the upper degree `n` is determined automatically from the length of the coefficient vector. Why not having the same behavior with LaurentPolynomial type? Namely, why not having 

```julia
julia> a = LaurentPolynomial([1,2,3,4],-2,:z)
LaurentPolynomial(z⁻² + 2*z⁻¹ + 3 + 4*z)
```
?
It is certainly a minor issue, yet the current implementation makes the relationship between these two type a bit less transparent - one always has to figure out the the *upper degree* while defining a Laurent polynomial when the *lower degree* would be just enough. 

By the way, having switched into the "review mode", I am also a bit unsure about naming the function that returns the range as `extrema`. Will not it seduce the user to think that it is an extrema of the values of the polynomial? Without a consulting a users guide, when encountering `max(p::Polynomial)` or `extrema(p::LaurentPolynomial)` in the code, I would certainly expect the value-related interpretation. If for some reason both `m` and  `n` parameters need to stay in the `LaurentType` definition, I think that something like `degrees()` returning a couple `(lowerdegree,upperdegree)` (or `(trailingdegree,leadingdegree)`) could be a more appropriate name. The `degree` function (without 's' at the end) would keep returning the upper degree as it does now because it than nicely handles the case when the lower degree of a Laurent polynomial is zero and the Laurent polynomial then looks like a standard polynomial.

What do you think about it? Maybe not reasonable. Maybe it is too late to make these fundamental changes, although I would guess that LaurentType has not found its way into too many projects yet and finetuning the design might help in the long run.

**Comment by jverzani** [comment]
Okay, I had some time to address this in #256

* left in the specification of a range, but the expectation is that just `m` is specified on construction
* I deprecated `extrema` and `range` as being confusing. I realized the generics `firstindex` and `lastindex` were already defined, and these map well (mentally) to the corresponding degrees, so I didn't define anything for the "lowerdegree".  Please let me know if you think they need a name more indicative of a degree.
