### ISSUE TITLE
Extend `isreal` & `real` for `Polynomial`?

### ISSUE THREAD

**Issue by singularitti** [JuliaMath/Polynomials.jl#258]
A polynomial having only real numbers as coefficients is called a _real polynomial_. Sometimes the polynomial has `Complex` coefficients but they are actually real, like `2 + 0im`. Hope the following methods could be added:

```julia
julia> p = Polynomial([2 + 0im, 3 - 0im, 4.5 + 0im])
Polynomial(2.0 + 3.0*x + 4.5*x^2)

julia> eltype(p)
Complex{Float64}

julia> isreal(p)
true

julia> real(p) == Polynomial([2, 3, 4.5])
true
```

**Comment by jverzani** [comment]
Something like this:

```
Base.isreal(p::Polynomials.AbstractPolynomial) = all(isreal, coeffs(p))
```

If that is what you want, care to put in a PR?

As for `real(p)`, this is a bit trickier, but something like this might work:

```
Base.real(p::P) where {P <: AbstractPolynomial}  = ⟒(P)(real(coeffs(p)), p.var)
```

**Comment by singularitti** [comment]
> If that is what you want, care to put in a PR?

Sure.

I know `⟒` means `constructorof`, how's it called, BTW?

**Comment by singularitti** [comment]
There are other concepts like

> [**zero polynomial**: The constant polynomial P(x)=0 whose coefficients are all equal to 0.](https://mathworld.wolfram.com/ZeroPolynomial.html)

> [**Integer Polynomial**: A polynomial having coefficients that are all integers.](https://mathworld.wolfram.com/IntegerPolynomial.html)

I don't think we can apply `iszero` & `zero`, `isinteger` & `Integer` there. Should we rename them to other things? Like

- `isrealpoly` to identify & `realpoly` to convert.
- `isintegerpoly` to identify & `integerpoly` to convert.
- `iszeropoly` to identify & `zeropoly` to convert. `zero` has been taken & it definitely means some other thing.

**Comment by jverzani** [comment]
The `⟒` is "upin" and chosen only as it goes "up" by stripping off parameters for the numeric type of the coefficients. I wanted something shorter than `constructorof` and that choice kinda looked right.

As for `iszero` it is defined in `common.jl` and satisfies `iszero(zero(p))` is `true`.  The "zero" polynomial plays the algebraic role of `0` in both addition and multiplication where the scalar `0` is identified with the polynomial `0`, so this naturally fits the generic usage.

As for other extensions, like `isrealpoly` I have some thoughts as to what should be defined and what can be left to a composition. Namely, I think that generically the view of a polynomial is that of an "array" with some special properties related to indexing (0-based save for `Legendre`), arithmetic (`*` is defined differently), storage (an "array" really is some container with `Vector` -> `Polynomial`, `OffsetVector` -> `Legendre`, `SparseVector` -> `SparsePolynomial`, and `NTuple` -> ImmutablePolynomial). With that, the methods that should be defined on a polynomial should also be defined on the vector `coeffs(p)`. 

So `isreal` makes great sense, as does `real` for conversion, as they are defined on vectors in Base Julia.

But `isinteger` does not have `isinteger([1,2,3])` being defined, so wouldn't make sense (taking a cue from base Julia for generics, not my on personal sense of "sense," which says if `isreal` is defined then why not `isinteger`. )

The patterns of `isXXX(p) = all(XXX, coeffs(p)` and `XXX(p) = ⟒(p)(XXX.(coeffs(p)), p.var)` seem like what should be provided through a higher order function. I'm thinking the package could provide (with more suitable names):
```
isXXX(fn, p) = all(fn, coeffs(p))
asXXX(fn, p::P) where {P <: AbstractPolynomial} = ⟒(P)(fn.(coeffs(p)), p.var)
```

And the user would define

```
Base.isinteger(p::AbstractPolynomial) = isXXX(isinteger, p)
asinteger(p::AbstractPolynomial) = asXXX(x -> convert(Integer, x), p)
```

Does that make sense to you?

**Comment by singularitti** [comment]
So you are saying we keep `isreal` & `real` as defined above, and define an `isXXX` for users to extend? I do think we could change the name to not be `isXXX`, maybe `iscoeffs`? It kind of composes a sentence "is `coeffs` `fn`?", like `isequal(x, y)`("is `x` equal to `y`?") .

> As for iszero it is defined in common.jl and satisfies iszero(zero(p)) is true. The "zero" polynomial plays the algebraic role of 0 in both addition and multiplication where the scalar 0 is identified with the polynomial 0, so this naturally fits the generic usage.

Ah, I get it. `Polynomial(0)` can be regarded as a polynomial with all coefficients `zero` (`Polynomial([0, 0, 0, 0]) == Polynomial(0)`). So it is already there.

**Comment by jverzani** [comment]
Yes, `isreal` and `real` for polynomials are straightforward analogies to how the two act on vectors, so they seem perfectly reasonable to assume they are defined for polynomials (and will be when you're done :)

Yes, isXXX is definitely not right. The problem for me with `iscoeff` is that `iscoeff` would, by analogy check if p is of some "coeff" type or has some "coeff" property, so it doesn't feel right. In `SymPy.jl` we have an  `is_(:symbol, x)` function playing a similar role. Maybe just `is_` or `as_`? Then for the user it would look like, for example:

```
isintegerpoly(p) = is_(x -> convert(Integer, x), p)
```

Though admittedly, that `is_` is really not meant for external consumption.

**Comment by singularitti** [comment]
Sure we can go `is_` or `as_`, just do not export them. Leave them for developers.
