### ISSUE TITLE
Add support for OffsetArrays as coefficients in Polynomial construction

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/Polynomials.jl#261]
Something like this doesn't work as expected

```julia
julia> using OffsetArrays

julia> coeffs = OffsetVector([0,0,1], 0:2)
3-element OffsetArray(::Array{Int64,1}, 0:2) with eltype Int64 with indices 0:2:
 0
 0
 1

julia> ChebyshevT(coeffs)
ChebyshevT(1⋅T_1(x))
```

I would have expected the polynomial to have a degree of 2.

This seems to be because https://github.com/JuliaMath/Polynomials.jl/blob/d17ec5144a00a4c0e86d6adcd54f1efa93dd5c21/src/polynomials/ChebyshevT.jl#L33 assumes that `coeffs` has 1-based indexing. This may perhaps be changed to use `begin` or `firstindex`?

**Comment by jishnub** [comment]
Attempting to create an `ImmutablePolynomial` with an `OffsetVector` fails with a `StackOverflowError`

```julia
julia> ImmutablePolynomial(ones(3:4))
ERROR: StackOverflowError:
Stacktrace:
 [1] ImmutablePolynomial{Float64,N} where N(::OffsetArray{Float64,1,Array{Float64,1}}, ::Symbol) at /home/jishnu/.julia/packages/Polynomials/Xs5GI/src/abstract.jl:49
 [2] ImmutablePolynomial(::OffsetArray{Float64,1,Array{Float64,1}}, ::Symbol) at /home/jishnu/.julia/packages/Polynomials/Xs5GI/src/abstract.jl:47
 ... (the last 2 lines are repeated 26151 more times)
 [52305] ImmutablePolynomial{Float64,N} where N(::OffsetArray{Float64,1,Array{Float64,1}}, ::Symbol) at /home/jishnu/.julia/packages/Polynomials/Xs5GI/src/abstract.jl:49
 [52306] ImmutablePolynomial(::OffsetArray{Float64,1,Array{Float64,1}}, ::Symbol) at /home/jishnu/.julia/packages/Polynomials/Xs5GI/src/abstract.jl:47 (repeats 2 times)
```

**Comment by jverzani** [comment]
What would be your expectation of the degree of `ImmutablePolynomial(ones(3:4))`? Degree 4?

**Comment by jishnub** [comment]
Yes, I would have expected such an array to provide the coefficients of `x^3` and `x^4`. Actually more pertinent is the case of `ChebyshevT(ones(0:2))`, where I would have expected a degree-2 polynomial as I had specified 3 coefficients.

However I realize that this goes against the standard adopted here, where the first index corresponds to the coefficient of `x^0` and so on, and the indices of the coefficient vector play no part. I guess I had expected something like this to work as the constructor accepts `AbstractVector`s and not just `Vector`s:

```
ChebyshevT{<:Number}(coeffs::AbstractVector, var=:x)
ImmutablePolynomial{T<:Number}(coeffs::AbstractVector{T}, var=:x)
````

Based on the present design, I wonder if it makes sense to use `Base.require_one_based_indexing` to explicitly indicate that something unexpected might happen if 1-based indexing is not used? Or perhaps warn the user that certain elements of the array are being ignored?
