### ISSUE TITLE
Use StaticVector instead of NTuple in ImmutablePolynomials

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/Polynomials.jl#265]
This leads to certain performance improvements, such as 

```julia
julia> p = ImmutablePolynomial(ones(20))

julia> @btime norm($(p.coeffs));
  60.203 ns (0 allocations: 0 bytes)

julia> s = SVector(p.coeffs);

julia> @btime norm($s);
  14.831 ns (0 allocations: 0 bytes)
```

**Comment by jverzani** [comment]
Hmm, this would add a dependency, which may be slow to load. But let me explore. It would be easy enough to create a new polynomial type and check. (Yesterday I saw your comment in your `polyfit` package about using SpecialMatrices and that makes a big difference there, so likely something here will help too.)

**Comment by jishnub** [comment]
Tbh `SpecialMatrices` helps in only one special case (with a square Vandermonde matrix). `StaticVector`s might be a more promising improvement, worth exploring.

**Comment by jverzani** [comment]
I did a quick test and realized I have to rework more of the backend than a quick test allowed. So until I get back to that, I did the reverse in #266 -- speeding up norm for a tuple using a generated function.

**Comment by jverzani** [comment]
Well, there are two ways to get a faster `norm`. One uses a faster `norm` from an external package, the other essentially copies that code into `polynomials`. If there are other performance improvements expected in #267, I'd like to hear.

**Comment by jverzani** [comment]
I opted for borrowing `norm` from `StaticArrays`. If there are other performance benefits that are not being leveraged now, this decision can certainly be revisited.
