### ISSUE TITLE
Feature request: support for modulo arithmetic in polynomial field

### ISSUE THREAD

**Issue by jakewilliami** [JuliaMath/Polynomials.jl#274]
E.g., over the field of integers mod 3, we might have
```julia
julia> using Polynomials

julia> p = Polynomial([1, 1, 2, 0, 1, 2, 1])
Polynomial(1 + x + 2*x^2 + x^4 + 2*x^5 + x^6)

julia> q = Polynomial([2, 1, 1])
Polynomial(2 + x + x^2)

julia> mod(rem(p, q), 3)
Polynomial(1.0*x + 1.0)

julia> a = Polynomial([0, 1, 0, 1, 0, 0, 1])
Polynomial(x + x^3 + x^6)

julia> b = Polynomial([1, 0, 1])
Polynomial(1 + x^2)

julia> mod(rem(a, b), 2)
Polynomial(1.0)
```
I am unsure how this would be implemented.  Would this be possible?

**Comment by jakewilliami** [comment]
Maybe something like this?
```julia
polymod(p::Polynomial, n::Integer) = Polynomial(mod.(p.coeffs, n))
remmod(p::Polynomial, q::Polynomial, n::Integer) = Polynomial(mod.(coeffs(rem(p, 1)), n))
```
Is this too simply to be work putting in the main Polynomials package?
Or is this easy enough to implement

**Comment by jverzani** [comment]
How far do you get to what you want when using a modulo number type. Something like

```
using Mods
F = Mod{3}
p = Polynomial(F[1,1,1])
iszero(3p)
```

**Comment by jakewilliami** [comment]
I think this should be closed, as it is easy enough to implement (given propositions from myself and @jverzani).  Reopen if anyone thinks it needs to be addressed.
