### ISSUE TITLE
Interpolation with many points.

### ISSUE THREAD

**Issue by marlloseff** [JuliaMath/Polynomials.jl#290]
Interpolation does not seem to work when the number of points is large. For example, f(x) = exp (-x), interpolates well with 30 points, but fails for 70 points. The exp function is just an example, it does not need many points, but in physics we deal with other situations that need many points. I appreciate if anyone can help. Thank you.

```julia
using Polynomials, PyPlot
function test()
    n = 70
    x = range(-4,4,length=n)
    y = exp.(-x)
    pol = fit(x,y)
    scatter(x,y)
    plot(x,pol.(x))	
    title("n = $(n)")	
end
```
Failure with n = 70.

![fig2](https://user-images.githubusercontent.com/33531557/97703755-e9cb6a80-1a8f-11eb-85da-04ea2c1bf617.png)

![fig3](https://user-images.githubusercontent.com/33531557/97707818-9f012100-1a96-11eb-8974-0bb18e3a7817.png)

Correct result with n = 30.

![fig1](https://user-images.githubusercontent.com/33531557/97703729-dfa96c00-1a8f-11eb-86ac-58028a568793.png)

I know it is possible to make a simple code and interpolate with a large n, but then I lose the other benefits of the Polynomials package, which are very good.

Additional Information:
Polynomials v1.1.10
PolynomialRoots v1.0.0                                                                                                       
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by martinholters** [comment]
I think it's not only the number of points which is the problem, but also the degree of the polynomial. E.g. using `pol = fit(x,y,29)` already improves the situation. And indeed, the higher the degree, the more numerically challenging the fitting. I still see a degradation for larger `n` however, which does not have a justification. Maybe we should apply something like the following?
```diff
--- a/src/common.jl
+++ b/src/common.jl
@@ -112,7 +112,7 @@ function _fit(P::Type{<:AbstractPolynomial},
     if weights !== nothing
         coeffs = _wlstsq(vand, y, weights)
     else
-        coeffs = pinv(vand) * y
+        coeffs = qr(vand) \ y
     end
     R = float(T)
     return P(R.(coeffs), var)
```
Then I get very similar results for `n=30` and `n=70` as long as I keep the degree at 29.

**Comment by marlloseff** [comment]
> I think it's not only the number of points which is the problem, but also the degree of the polynomial. E.g. using `pol = fit(x,y,29)` already improves the situation. And indeed, the higher the degree, the more numerically challenging the fitting. I still see a degradation for larger `n` however, which does not have a justification. Maybe we should apply something like the following?
> 
> ```diff
> --- a/src/common.jl
> +++ b/src/common.jl
> @@ -112,7 +112,7 @@ function _fit(P::Type{<:AbstractPolynomial},
>      if weights !== nothing
>          coeffs = _wlstsq(vand, y, weights)
>      else
> -        coeffs = pinv(vand) * y
> +        coeffs = qr(vand) \ y
>      end
>      R = float(T)
>      return P(R.(coeffs), var)
> ```
> 
> Then I get very similar results for `n=30` and `n=70` as long as I keep the degree at 29.

**Comment by marlloseff** [comment]
#

**Comment by marlloseff** [comment]
Curious, with this change, it works from degree = max_degree - 1.

![fig1](https://user-images.githubusercontent.com/33531557/97732110-ce268b00-1ab4-11eb-990c-a8ae57a141dc.png)

**Comment by martinholters** [comment]
Should probably also look at `_wlstsq`.

**Comment by marlloseff** [comment]
Derivative and integral test. This magnitude of error (at the ends) makes me a little worried.

```julia
using Polynomials, PyPlot, Statistics

function test_derivative()
	n = 70
	x = range(-4, 4, length=n)
	y = exp.(-x)
	pol = derivative(fit(x, y, n-2))
	subplot(1, 2, 1)
	scatter(x, -y) # derivative dy/dx = -y for exp
	plot(x, pol.(x)) # derivative fit
	subplot(1, 2, 2)
	plot(x, pol.(x) .+ y) # error: pol-(-y)
	suptitle("Derivative, n = $(n)")
	println(mean(pol.(x) .+ y)) # 1.1e-6			
end

function test_integral()
	n = 70 
	x = range(-4, 4, length=n)
	y = exp.(-x)
	pol = integrate(fit(x, y, n-2))
	subplot(1, 2, 1)
	scatter(x, 1 .- y) # integrate ∫ydx = 1-y -- [0,x]
	plot(x, pol.(x)) # integrate fit
	subplot(1, 2, 2)
	plot(x, pol.(x) .+ y .- 1) # error: pol-(1-y)
	suptitle("Integrate, n = $(n)")
	println(mean(pol.(x) .+ y .- 1)) # -5.4e-10		
end
```
![fig5](https://user-images.githubusercontent.com/33531557/97757223-1658a400-1adb-11eb-844a-c4aa628a32f8.png)

![fig6](https://user-images.githubusercontent.com/33531557/97757248-1eb0df00-1adb-11eb-9a88-96c1583b00f7.png)

**Comment by marlloseff** [comment]
Martin Holters, thanks for your reply. Helped me a lot.

**Comment by jverzani** [comment]
Following up on this, in case it is still of interest, someone on discourse pointed out this work: https://arxiv.org/abs/1911.09988 which I need to integrate into `Polynomials` somehow for large `n`. But using that technique we have:

```
julia> y = exp.(-x);

julia> n = 70
70

julia> x = range(-4,4,length=n)
-4.0:0.11594202898550725:4.0

julia> y = exp.(-x);

julia> d, H = polyfitA(x, y, n-1);

julia> maximum(abs, polyvalA(d, H, x) - y)
1.1324274851176597e-14

julia> p = fit(Polynomial, x, y, n-1);

julia> maximum(abs, p.(x) - y)
7.924475561182053e7
```

Using this pair of functions:

```

"""
    polyfitA(x, y, n)

Fit a degree ``n`` or less polynomial through the points ``(x_i, y_i)`` using Arnolid orthogonalization.

The use of a Vandermonde matrix to fit a polynomial to data is ill-conditioned for larger values of ``n``. This orthogonalization fixes this problem.

References:
VANDERMONDE WITH ARNOLDI
PABLO D. BRUBECK, YUJI NAKATSUKASA, AND LLOYD N. TREFETHEN∗
arXiv:1911.09988 (https://people.maths.ox.ac.uk/trefethen/vander_revised.pdf)

Example:

```
f(x) = 1/(1 + 25x^2)
N = 80; xs = [cos(j*pi/N) for j in N:-1:0];
d,H = polyfitA(xs, f.(xs), N-1);
p = fit(Polynomial, xs, f.(xs))   
maximum(abs, p(x) - f(x) for x ∈ xs) # 3.304586010148457e16
maximum(abs, polyvalA(d, H, xs) - f.(xs)) # 4.932472894014772e-8
```

!!! Note:
    `polyvalA` is vectorized in the `x` value, avoiding the internal construction of two matrices for each separate computation.

"""
function polyfitA(x, y, n)
    m = length(x)
    T = eltype(y)
    Q = ones(T, m, n+1)
    H = zeros(T, n+1, n)
    @inbounds for k = 1:n
        q = x .* Q[:,k]
        for j in 1:k
            H[j,k] = (Q[:,j]' * q)/m
            q -= H[j,k] * Q[:,j]
        end
        H[k+1,k] = norm(q)/sqrt(m)
        Q[:,k+1] = q/H[k+1,k]
    end
    d = Q \ y
    d, H
end

# s can be a vector here to avoid construction of
# the matrices M, W for each x ∈ s
function _polyvalA(d, H, s)
    T = eltype(H)
    n = size(H, 2)
    M = length(s)
    W = ones(T, M, n+1)
    @inbounds for k = 1:n
        w = s .*  W[:,k]
        for j in 1:k
            w -= H[j,k] * W[:,j]
        end
        W[:,k+1] = w/H[k+1,k]
    end
    W*d
end

"""
    polyval(d, H, s)

Evaluate the polynomial returned by `polytfitA` at `s`.

The value of `s` can be a scalar or container.

See [`polyfitA`](@ref) for reference and examples.
"""
polyvalA(d, H, s) = _polyvalA(d, H, s)
polyvalA(d, H, s::Number) = _polyvalA(d,H,s)[1]
```
