### ISSUE TITLE
Inconsistency in Polynomial creation based on the type of the AbstractVector argument

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/Polynomials.jl#302]
Currently the way `Vector`s and `AbstractVector`s are treated is different, which results in seemingly inconsistent behavior such as 

```julia
julia> using OffsetArrays, Polynomials

julia> a = [1,1];

julia> b = OffsetVector(a, axes(a,1));

julia> a == b
true

julia> Polynomial(a)
Polynomial(1 + x)

julia> Polynomial(b)
Polynomial(x + x^2)

julia> Polynomial(a) == Polynomial(b)
false
```

It would be nice to have these two return the same result.

While it might not be possible to fix this in a non-breaking way, I'd argue that this behavior is a bug and should not be relied upon.

**Comment by jishnub** [comment]
In the meanwhile it would be good to document this behavior in the docstring. Currently the docstring for `Polynomial` seems to indicate that the behavior is identical for all `AbstractVector`s

**Comment by jverzani** [comment]
At one point I thought it cute that various abstract vector types naturally map to different polynomial types, but using the `Polynomial` constructor was confusing, as you discovered. I'll have to fix this. (I never documented it, so I don't really consider it breaking, though ...)

**Comment by jishnub** [comment]
Perhaps `Polynomial` should ignore axes altogether and treat any `AbstractVector` as a list, while `LaurentPolynomial` can derive the range of coefficients from the axes. This should be in accordance with the documented behavior, and also avoid inconsistencies.
