### ISSUE TITLE
Implementing named polynomial sequences.

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaMath/Polynomials.jl#311]
In class today, I encountered Hermite polynomials, and the teacher demonstrated that they are implemented in MatLab. I quickly navigated to `Polynomials.jl` to see if Julia had the same fancy functionality - it unfortunatly seems like only Laurent and Chebychev polynomials are implemented as of right now. Should any more named polynomials from [this wikipedia list](https://en.wikipedia.org/wiki/List_of_polynomial_topics#Named_polynomials_and_polynomial_sequences) be added?

Maybie a new package `NamedPolynomials.jl` could be created, based on the API and types of `Polynomials.jl`, if there is motavation behind it. I am coming from a "would be cool" perspective, but it might prove useful/needed to others.

**Comment by jverzani** [comment]
Checkout [SpecialPolynomials](https://github.com/jverzani/SpecialPolynomials.jl) for this. 

That is a long list from Wikipedia, many of which are not covered in SpecialPolynomials and could be.

I haven't checked, as it is new, but this package [ClassicialOrthongonalPolynomials](https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl) also covers the same ground, and likely in a more performant manner.

**Comment by KronosTheLate** [comment]
That would be exacly what I was thinking of :D Thanks.

Is there any possibility that one of them (or a third package) could be an "official partner" of Polynomials.jl, in the sense that the documentation would point to it if one should need an implementation of special/named/orthogonal polynomials?

**Comment by jverzani** [comment]
Yes, good idea. The most partner-like would be `SpecialPolynomials` but for many performance is more critical than the design, so I'd also add `ClassicalOrthogonalPolynomials`. (At one point `SpecialFunctions` had a PR to add some of these polynomials. I guess checking on the status of that is a good idea too). I'll add a note to both somewhere (likely in ChebyshevT as a note, but also where the other polynomial packages are listed), unless you beat me to it :)

**Comment by KronosTheLate** [comment]
I gotta admit that I am pretty unfomfortable with actually making things happen, as I am very insecure about the best/right way to go about it. When I have an idea I normally just post it, and hope that the people more involved with the project can see the right way to make it happen.

Like in this case, I don't know if one should contact the creators of the previously mentioned packages and ask them to tweak _their_ package to meet _my_ vision, or try and create a new one that is affiliated with Polynomials.jl in some way. But I am not competent enough, or have the time, to myself implement what I am greedily asking for.

Now that is more about me that the issue, with the point being that I am unlikely to beat you to it xD

**Comment by JeffreySarnoff** [comment]
for reenforcement purposes:
It is perfectly appropriate to pass along a third-party request that is better suited to another package.
Just copy the request as new issue of that other package and at-sign identify the requestor in the new issue.

**Comment by jverzani** [comment]
CLosed with #328. Thanks.
