### ISSUE TITLE
Feature request: Matrix-valued polynomials

### ISSUE THREAD

**Issue by sverek** [JuliaMath/Polynomials.jl#349]
Would be great to be able to have matrices as coefficients to polynomials, for example,

```
LaurentPolynomial([[1 2;3 4],[5 6;7 8],[10 11;12 13]],-1)
```

Works in ApproxFun.jl

**Comment by jverzani** [comment]
Yeah, #234 made some attempts here, but I never merged it in. The main issue (there are others) is we expect some things to be available from the type `T`, such as `one(T)`, ... and for a matrix that isn't the case, though for `StaticArrays` it is. At the time of #234, even the symbol wasn't in the polynomial type. Now it is. I'll have a look to see how far we can get now.

**Comment by sverek** [comment]
Thanks! :)

**Comment by jverzani** [comment]
Closed by #350
