### ISSUE TITLE
Support for Newton Polynomials (Newton basis)

### ISSUE THREAD

**Issue by JakobSachs** [JuliaMath/Polynomials.jl#368]
I was interested if theres some planned support for Newton Polynomials ?
So polynomials in the Newton Basis:

![Newton Basis](https://wikimedia.org/api/rest_v1/media/math/render/svg/227efa64e8b5301108a7a5da5cbbb86dcf59af04)

I tried to have a look into writing something already, but havent gotten far.
Is this already a thing and have i just overlooked it ? If not, then i would be willing and interested to help.
Thanks ^^

**Comment by jverzani** [comment]
There is in [`SpecialPolynomials`](https://github.com/jverzani/SpecialPolynomials.jl). Let me know if that is sufficient for your usage or if you have better ideas on how to implement that.

**Comment by JakobSachs** [comment]
Oh yeah well... thats pretty much what i was looking for, thanks.
