### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by andreasvarga** [JuliaMath/Polynomials.jl#369]
I wonder if there is a simple way to evaluate an `m x n` polynomial matrix `P` for a constant value `val`, without explicitly using loops:
```
 for i = 1:m
      for j = 1:n
           Val[i,j] = P[i,j](val)
      end
 end
```

**Comment by jverzani** [comment]
Broadcasting can do this. Here is one way:

```
apply(f,x) = f(x)
apply.(A, x)
```

However, `apply` is `x |> f` so this could also be done in one line with

```
x .|> A
```

**Comment by andreasvarga** [comment]
Thanks. ` x .|> A` is exactly what I expected.
