### ISSUE TITLE
Function for getting polynomial variable as symbol

### ISSUE THREAD

**Issue by XInvisib1eX** [JuliaMath/Polynomials.jl#382]
[GaloisFields](https://github.com/tkluck/GaloisFields.jl) uses this package and compatibility is set for older versions because they use `poly.var` to get variable as `Symbol`

A simple function

```julia
getvar(p::AbstractPolynomial{T,X}) where {T, X} = X
```

...allows to update dependency GaloisFields to the latest version (all tests passed)

**Comment by jverzani** [comment]
We have ‘indeterminate’ to do this task.  Does that help, or does it need to be ‘getvar’?

**Comment by XInvisib1eX** [comment]
Yes, that solves, didn't find this in docs.
