### ISSUE TITLE
Should `SparsePolynomial` support negative exponents?

### ISSUE THREAD

**Issue by jishnub** [JuliaMath/Polynomials.jl#409]
Currently, I think it does, but certain methods need to be specialized to fully deal with this. This is a regression introduced in ddb9e57fd6085c1a061ae0be1b273d3416e2cc67, where `firstindex` etc. were made to fall back to default implementations. (sorry about this, but I can submit a fix) 

```julia
julia> SparsePolynomial(Dict(-1=>3, 2=>4))
SparsePolynomial(4*x^2)
```

**Comment by jverzani** [comment]
Good question. Either an error or we could also treat SparsePolynomials like Laurent polynomials. That might be desirable and I don't think it would be too difficult to implement. But dropping the term without comment needs to be fixed. Any thoughts on what you would like to see?

**Comment by jishnub** [comment]
I think it makes sense to make it accept negative exponents. Ideally, any polynomial should have a sparse representation.
Currently, the term isn't dropped, but `firstindex` incorrectly falls back to the default value of `0`. It should not be too difficult to fix this.
