### ISSUE TITLE
Can't take dot products of vectors of polynomials

### ISSUE THREAD

**Issue by Timeroot** [JuliaMath/Polynomials.jl#424]
It seems that `dot` was once defined for Polynomials but was removed (in 2017), for reasons I don't understand. This leads to a very frustrating behavior, where vectors of Polys can't be contracted together, e.g.
```
> xx = [Polynomial([2,3]), Polynomial([5,6,7])];
> yy = [Polynomial([1]), Polynomial([2,3])];
> println(length(xx))
> println(length(yy))
> dot(yy, xx)
2
2
DimensionMismatch("x and y are of different lengths!")

Stacktrace:
 [1] dot(x::Polynomial{Int64, :x}, y::Polynomial{Int64, :x})
   @ LinearAlgebra C:\Users\AlexanderMeiburg\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:900
 [2] dot(x::Vector{Polynomial{Int64, :x}}, y::Vector{Polynomial{Int64, :x}})
   @ LinearAlgebra C:\Users\AlexanderMeiburg\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:915
 [3] top-level scope
   @ In[213]:5
 [4] eval
   @ .\boot.jl:373 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1196
```
even though `xx[1]*yy[1] + xx[2]*yy[2]` works just fine. This is because LinearAlgebra's `dot` method assumes a functioning implementation of `dot` on the underlying scalar type (here, a Polynomial), and that is currently not defined for Polynomials. It seems good to define
```
dot(x::Polynomial, y::Polynomial) = conj(x)*y
```
then. If there are too many objections about this leading to conflicts with other notions of dot for e.g. orthogonal polynomials, then perhaps we could do
```
dot(xv::AbstractArray{T}, yv::AbstractArray{T}) where {T <: Polynomial} = sum(conj(x)*y for (x,y) = zip(xv, yv))
```
which I think should avoid any conflicts.

**Comment by jverzani** [comment]
Yes, `dot` was removed as it was just for syntactic reasons (it was cute to use it for multiplication in printing which allowed a copy and paste). So, bringing it back should likely match some mathematical usage. These polynomials are basically viewed as 0-based vectors, so I'm not sure 

```
dot(x::Polynomial, y::Polynomial) = conj(x)*y
```

is what people would expect. Do you have a reference for the proposed choice? Or for the definition you really want, which is the latter?

For orthogonal polynomials, sure dot(p,q) makes sense as an integral, but that isn't a great definition for standard basis polynomials, so I'm not terribly concerned about that specialized usage.

**Comment by Timeroot** [comment]
Mm, I see that if you're viewing the polynomials as vectors themselves then the dot on the Polys themselves could be surprising, yes. I was using dot products of vectors of polynomials in a quantum context -- if you think of, say, a spin-1 particle in a 1D box with bounds `[a,b]`, and its wavefunction given by polynomials, then you represent that wave vector by a length 3 vector `v` of polynomials. The resulting density function is `dot(v, v)`, the inner product between two quantum states `v1` and `v2` is `integrate(dot(v1,v2), a,b)`, the expectation of its position can be computed by `integrate(dot(v, Polynomial([0,1]) .* v), a,b)`, and so on.
