### ISSUE TITLE
Strangeness with printout of Polynomial with complex coefficients

### ISSUE THREAD

**Issue by gvdeynde** [JuliaMath/Polynomials.jl#427]
I think there is somewhere a flaw in the printout. It seems the math is correct, though... For as far as this very simple example goes...

Julia 1.7.3 and Polynomials 3.1.3

```julia
using Polynomials
```

```julia
b = 5. +8im
```

    5.0 + 8.0im

```julia
pb = Polynomial([b])
```

5.0 &#43; 8.0im

```julia
pb(1.0)
```

    5.0 + 8.0im

```julia
pmb = Polynomial([-b])
```

&#45;5.0 &#43; 8.0im

```julia
pmb(1.0)
```

    -5.0 - 8.0im

```julia
q = Polynomial([1, b])
```

1.0 &#43; (5.0 &#43; 8.0im)x

```julia
q(1.)
```

    6.0 + 8.0im

```julia
mq = Polynomial([1,-b])
```

1.0 &#45; (5.0 &#43; 8.0im)x

```julia
mq(1.0)
```

    -4.0 - 8.0im

```julia

```

**Comment by jverzani** [comment]
Yikes. I'll have a look. Thanks!

**Comment by jverzani** [comment]
I have a PR ready for this https://github.com/JuliaMath/Polynomials.jl/pull/428

Waiting to see if there are any comments. 

Thanks for reporting the issue!
