### ISSUE TITLE
Get coefficient from Symbolics.jl's expression?

### ISSUE THREAD

**Issue by phpsmarter** [JuliaMath/Polynomials.jl#437]
I want to write more algebraic style code , so do this 

here is the code for  eigen  polynomials with pluto note

1. get  algebraic expression with  symbolcs.jl

```julia
 using  Symbolics, LinearAlgebra, RowEchelon, Latexify , Polynomials
 @variables A,λ,I, poly
  A=[-5 2;-7 4]
  I= diagm([1,1])
  poly=det(A-λ*I)
  res=expand(poly)
  latexify(res~0)
```

so , I can get   eigen  polynomial of  matrices. 

2. find  eigen value

```julia
     poly=Polynomial([-6,1,1],:λ)
     roots=roots(poly)
```
 could get coefficients from  symbolics expression directly?

**Comment by jverzani** [comment]
I think you want to bypass `Polynomials`, right? If so, I found this [thread](https://github.com/JuliaSymbolics/Symbolics.jl/issues/216) to be helpful:

```
julia> Symbolics.value(res).dict
Dict{Any, Number} with 2 entries:
  λ^2 => 1
  λ   => 1
```

That thread is a year old, perhaps there is another solution out there.

**Comment by phpsmarter** [comment]
> I think you want to bypass `Polynomials`, right? If so, I found this [thread](https://github.com/JuliaSymbolics/Symbolics.jl/issues/216) to be helpful:

Thanks. This is exactly what I want 

### get eigen value of matrix by symbolics algebra

```julia
let
 @variables A,λ,I,x,poly
  A=[3 0 2; 6 4 3; -4 0 -3]
  I=diagm([1,1,1])  
  poly=(A-λ*I)|>det|>expand     # characteristic polynomial of matrix
  coffes_dict = Symbolics.value(poly).dict
  dd = Dict(Symbolics.degree(first(kv)) => kv[2] for kv ∈ coffes_dict)
  dd[0] = substitute(poly, Dict(λ=>0)).val
  characteristicpoly= SparsePolynomial(dd, :λ)
  roots=roots(characteristicpoly)
end 
```

**Comment by jverzani** [comment]
Hi, I'm closing this. Re-open if I read the conclusion wrong.
