### ISSUE TITLE
Is the `order` function still defined?

### ISSUE THREAD

**Issue by singularitti** [JuliaMath/Polynomials.jl#457]
I cannot find the definition of it: https://github.com/JuliaMath/Polynomials.jl/blob/efeb4663b716a13bdcd21e829b4d2854fc5e385d/src/common.jl#L9

**Comment by jverzani** [comment]
Nice catch. I think that evolved into `degree`. Should have a deprecation warning. Do you want to put in a PR?

**Comment by singularitti** [comment]
Sure.

**Comment by singularitti** [comment]
Closed by #461
