### ISSUE TITLE
error on integrate or differentiate

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaMath/Polynomials.jl#467]
A naive user (like) me, would expect the polynomial fit function to return a `Polynomial` on which you can apply `integrate` or `differentiate`. Yet this is not the case:
```julia
julia> pa = Polynomials.fit(ArnoldiFit, 1:10, rand(10), 2)
ArnoldiFit of degree 2

julia> integrate(pa)
ERROR: MethodError: no method matching showterm(::IOContext{IOBuffer}, ::Type{ArnoldiFit{Float64, Matrix{Float64}, :x}}, ::Float64, 
::Symbol, ::Int64, ::Bool, ::MIME{Symbol("text/plain")})
...
```
At first sight this seems a relatively obscure error message suggesting a bug. Closer inspection reveals that the fit does not return a `Polynomial`, however, it would be nice, if the functions `differentiate` or `integrate` could either work with that type (automatic conversion into a Polynomial), or yield a specific error message, so the user immediately knows how to fix this. Converting into a `Polynomial` seems to be fine:
```julia
julia> pa = integrate(Polynomial(Polynomials.fit(ArnoldiFit, 1:10, rand(10), 2)))
Polynomial(0.6600277317226237*x + 0.0013508026984332877*x^2 - 0.0005524878618416857*x^3)
```
Also it would be nice, if the help message for `integrate` and `differentiate` contained a simple example, how to use them.

**Comment by jverzani** [comment]
Thanks for the feedback. The issue with automatic conversion is that it can be really lossy for big degrees. That particular type, `ArnoldiFit`, is best suited for evaluation, as implemented. I'll look into whether there are ways to implement integration and differentiation without conversion. If not, I'll add error messages with a suggestion and a warning about potential loss of accuracy in the conversion.

**Comment by RainerHeintzmann** [comment]
Sounds great. If there is a way to integrate it and still return an "Arnoldi"-Polynome, that would also work, I guess.
