### ISSUE TITLE
how to skip specific degree?

### ISSUE THREAD

**Issue by Moelf** [JuliaMath/Polynomials.jl#469]
is it possible to fit to only `a*x^2 + b*x^3` for example?

**Comment by jverzani** [comment]
Nothing built in. You could do something like this to fit (x,y) to your poly:

```
X = diagm(x)
e = one.(x)
a, b = [X^2*e X^3*e] \ y
Polynomial([0,0,a,b])
```

**Comment by jverzani** [comment]
> I'm thinking as an interface maybe
> 
> ```julia
> julia> fit(xs, ys, [2,3])
> ```
> 
> would work

This evolved just a bit in #472. One can
* specify the coefficients to be estimated with least squares (as you do with `[2,3]`, though any old iterable container should work)
* specify fixed non-zero constants

The asymmetry in how the two are specified is convenient, though maybe a bit odd (We can use a container, like you suggest for the fitted non-zero coefficients, but need to specify index/coefficient pairs to specify any non-zero constants.)

Anyways, if you have any thoughts on this let me know.
