### ISSUE TITLE
Poly() not defined

### ISSUE THREAD

**Issue by Crohayd** [JuliaMath/Polynomials.jl#508]
Hi, I'm newbie in Julia. I used the function "Poly()" which gave me the same result as "Polynomial()" in this package the day before yesterday and it worked. However, I didn't change anything in my code but it seems not work today. It said "Poly not defined". I've tried restarting the PC, remove and add this package and it didn't work. If there were something that I ignored, I'm seeking for help. Thanks.

**Comment by Crohayd** [comment]
![Image](https://github.com/JuliaMath/Polynomials.jl/assets/125801528/8798d3cf-a2c2-4bd6-8115-2f2717fd8c0f)
Up is Julia and bottom is the Visual Studio Code.

**Comment by jverzani** [comment]
Poly is an old (very old) name. It is now `Polynomial`. If you really want to use it, you can run `julia> using Polynomials.PolyCompat` prior.
