### ISSUE TITLE
Should `AbstractPolynomial` subtype `Function`?

### ISSUE THREAD

**Issue by nsajko** [JuliaMath/Polynomials.jl#516]
Since `AbstractPolynomial` types are required to be callable, wouldn't it make sense to change the definition from
```julia
abstract type AbstractPolynomial{T,X} end
```
to
```julia
abstract type AbstractPolynomial{T,X} <: Function end
```

Then polynomials would be accepted anywhere functions are.

**Comment by jverzani** [comment]
Yeah, this has come up with plotting recipes as useful. I've always been wary, as I'm a bit biased towards the interpretation that polynomials are more like abstract vectors with an offset.

**Comment by nsajko** [comment]
Makes sense.
