### ISSUE TITLE
polynomials should have `big` methods?

### ISSUE THREAD

**Issue by nsajko** [JuliaMath/Polynomials.jl#522]
For example:
```julia-repl
julia> big(Polynomial(rand(3)))
ERROR: MethodError: no method matching big(::Polynomial{Float64, :x})
```

I would expect `big(::Polynomial{Float64, :x})` to return a value of type `Polynomial{BigFloat, :x}`.

**Comment by jverzani** [comment]
Here I say, we should follow vector as a guide. There we don't have `big([1,2,3])` defined. Of course there we have either `big.([1,2,3])` or `map(big,[1,2,3])`. For polynomials, `map(big,p)` would be the proper way, as the broadcast semantics are different for polynomials than vectors. (Which is maybe a mistake, but one made a long time ago and not really possible to change.)

**Comment by nsajko** [comment]
Didn't occur to me that `map` would work. `map(big, polynomial)` indeed works fine, thank you.
