### ISSUE TITLE
Question about using

### ISSUE THREAD

**Issue by lesobrod** [JuliaMath/Polynomials.jl#555]
Hello! I need to find roots of s.c. 0,1 - polynomials with high degrees many times.
More exactly I need just number of real roots, [see detailed here](https://math.stackexchange.com/questions/4839115/number-of-real-roots-of-0-1-polynomial).
Which package is the most suitable for it?

**Comment by jverzani** [comment]
So, `Polynomial.roots` will not be suitable for degrees above 50 or so, if even. The `AMRVW` package can do much better, but for your problem a specialized algorithm is likely the way to go. The `RealPolynomialRoots` package is intended to this, but doesn't scale to large polynomials well, as it doesn't have some more asymptotically efficient algorithms implemented (just naive ones). So... I'd suggest trying Nemo (https://nemocas.github.io/Nemo.jl/v0.13/polynomial.html#Root-finding-1) which uses the arb library under the hood and has the isolating algorithms you likely need.

**Comment by lesobrod** [comment]
Aha, thank you very much!
