### ISSUE TITLE
Polynomials requiring MakieCore

### ISSUE THREAD

**Issue by KsymenaPoradzisz** [JuliaMath/Polynomials.jl#580]
Hello. There is an issue that Polynomials require MakieCore. I tried what is proposed in the warning/error below but is still does not resolve the issue 

┌ Warning: Error requiring `MakieCore` from `Polynomials`
│   exception =
│    LoadError: ArgumentError: Package Polynomials does not have MakieCore in its dependencies:
│    - You may have a partially installed environment. Try `Pkg.instantiate()`
│      to ensure all packages in the environment are installed.
│    - Or, if you have Polynomials checked out for development and have
│      added MakieCore as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with Polynomials
│    Stacktrace:
│      [1] macro expansion
│        @ ./loading.jl:1167 [inlined]
│      [2] macro expansion
│        @ ./lock.jl:223 [inlined]
│      [3] require(into::Module, mod::Symbol)
│        @ Base ./loading.jl:1144
│      [4] include(mod::Module, _path::String)
│        @ Base ./Base.jl:419
│      [5] include(x::String)
│        @ Polynomials ~/.julia/dev/Polynomials/src/Polynomials.jl:6
│      [6] top-level scope
│        @ ~/.julia/packages/Requires/Z8rfN/src/Requires.jl:40
│      [7] eval
│        @ ./boot.jl:368 [inlined]
│      [8] eval
│        @ ~/.julia/dev/Polynomials/src/Polynomials.jl:6 [inlined]
│      [9] (::Polynomials.var"#195#198")()
│        @ Polynomials ~/.julia/packages/Requires/Z8rfN/src/require.jl:101
│     [10] macro expansion
│        @ ./timing.jl:382 [inlined]
│     [11] err(f::Any, listener::Module, modname::String, file::String, line::Any)
│        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:47
│     [12] (::Polynomials.var"#194#197")()
│        @ Polynomials ~/.julia/packages/Requires/Z8rfN/src/require.jl:100
│     [13] withpath(f::Any, path::String)
│        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:37
│     [14] (::Polynomials.var"#193#196")()
│        @ Polynomials ~/.julia/packages/Requires/Z8rfN/src/require.jl:99
│     [15] #invokelatest#2
│        @ ./essentials.jl:729 [inlined]
│     [16] invokelatest
│        @ ./essentials.jl:726 [inlined]
│     [17] foreach(f::typeof(Base.invokelatest), itr::Vector{Function})
│        @ Base ./abstractarray.jl:2774
│     [18] loadpkg(pkg::Base.PkgId)
│        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:27
│     [19] #invokelatest#2
│        @ ./essentials.jl:729 [inlined]
│     [20] invokelatest
│        @ ./essentials.jl:726 [inlined]
│     [21] run_package_callbacks(modkey::Base.PkgId)
│        @ Base ./loading.jl:869
│     [22] _tryrequire_from_serialized(modkey::Base.PkgId, path::String, sourcepath::String, depmods::Vector{Any})
│        @ Base ./loading.jl:944
│     [23] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
│        @ Base ./loading.jl:1028
│     [24] _require(pkg::Base.PkgId)
│        @ Base ./loading.jl:1315
│     [25] _require_prelocked(uuidkey::Base.PkgId)
│        @ Base ./loading.jl:1200
│     [26] macro expansion
│        @ ./loading.jl:1180 [inlined]
│     [27] macro expansion
│        @ ./lock.jl:223 [inlined]
│     [28] require(into::Module, mod::Symbol)
│        @ Base ./loading.jl:1144
│     [29] include(mod::Module, _path::String)
│        @ Base ./Base.jl:419
│     [30] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:303
│     [31] _start()
│        @ Base ./client.jl:522
│    in expression starting at /home/korizekori/.julia/dev/Polynomials/ext/PolynomialsMakieCoreExt.jl:1
└ @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:51

**Comment by jverzani** [comment]
Just to narrow down the issue, what Julia version are you using?

**Comment by KsymenaPoradzisz** [comment]
I use 1.8.1 Julia version and this error only occured while iI used Polynomials and CairoMakie in one file. Without CairoMakie this error was not appearing

**Comment by jverzani** [comment]
Do you the latest version? (The last one was supposed to have fixed this issue.)

**Comment by KsymenaPoradzisz** [comment]
Okay, now the issue is fixed hence I close this issue. Thank you!
