### ISSUE TITLE
Add support for different `show`s

### ISSUE THREAD

**Issue by aytekinar** [JuliaMath/Polynomials.jl#77]
### Description

Looking at the current `show`, I think it does an amazing job.

Do you think we could extend `show` to have

- support for printing the polynomial in the reverse order, and/or,
- printing the polynomial in its factored form?

### Motivation

We are working on a control systems toolbox, and we are requiring `Polynomials` in that toolbox. Generally, people in the control community prefer seeing the polynomials

- in descending exponents, if the system model is represented by transfer functions, or,
- in factored form such as `(s+r1)(s+r2)` for real roots (with corresponding multiplicities), or, `(s^2+as+b)` for complex conjugate roots, if the system is represented by zero-pole-gain models.

As a side note, in transfer function models, we are using a subset of the polynomials: polynomials with real coefficients. As a result, we can also have an efficient search strategy for `Poly{T<:Real}`s  when finding the complex conjugate pairs.

### Some Suggestions

We can have this behaviour (if that would be implemented in `Polynomials`), by

- either proper method overloads, or,
- maybe through a global setting in the package (maybe a `const Dict{Symbol,Any}` with a setting symbol pointing to a value type such as `Show{:Factored}`, `Show{:Descending}` and/or `Show{:Ascending}` to dispatch the corresponding `print` method for `show`, for example.

**Comment by jverzani** [comment]
Implementing this first would likely involve just generalizing `printpoly` and then figuring out the proper way to call it. I'm not sure how that should be done. 

As for the second, I have a new package `PolynomialFactors` that can factor over the integers modest-sized polynomials. I show the factors in a dictionary so it is clear to a user how to manipulate them, maybe in factored form would be more suitable and not much trouble. But that doesn't really help you, as your polynomials aren't restricted to integer or rational coefficients, so even the act of factoring isn't so easy if multiple roots are common.

**Comment by aytekinar** [comment]
Correct. In our case, since we are dealing polynomials having real coefficients, we have roots in conjugate pairs. I am planning to keep one of the pairs (in this case, the one with the positive imaginary part, for example). Then, at least, I would not need to care much about pairing them.

As for the first (reversed order printing), I would be more than happy seeing such an option. (Maybe I can also come up with a PR if needed).

**Comment by martinholters** [comment]
I'd actually like to see `printpoly` be made part of the public API to be able to show a polynomial (or convert it to a string) without the surrounding `Poly(...)`, and with the possibility to request reverse ordering. (And also an option to appreciate any powers part of the variable, e.g. `printpoly(Poly([1,2,3], "z^-1"), collapse_powers=true)` should give `"1 + 2*z^-1 + 3*z^-2"`.)

Unless this is considered a bad idea (or someone happens to be working on it already), I'd be willing to tackle it. Should I?

**Comment by aytekinar** [comment]
Actually, I would like to have the representation without the `Poly(...)` surrounding 👍 
Reverse ordering also sounds great!

**Comment by jverzani** [comment]
The only reason I worked on this was to have the printed output be copy-and-pasteable and to have printing work with some other number types (like the GF(2) example). I'm not sure who is wed to the enclosing `Poly` or the ordering, though I would think the default should match that expected by the constructor. Looking forward to what you come up with.
